server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spotyfy?createDatabaseIfNotExist=true
    username: root
    password: welcome@2021
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true